version: '2'
services:
   master:
     image: dylanmei/zeppelin
     #command: bash -c "/usr/spark-2.0.1/bin/spark-class org.apache.spark.deploy.master.Master -h master & /usr/zeppelin/bin/zeppelin.sh"
     hostname: master
     environment:
       ZEPPELIN_PORT: 8070
       MASTER: spark://master:7077
       #MASTER: local[*]
       SPARK_CONF_DIR: /conf
       SPARK_PUBLIC_DNS: localhost
       SPARK_MASTER_WEBUI_PORT: 8076
     expose:
       - 7001
       - 7002
       - 7003
       - 7004
       - 7005
       - 7006
       - 7077
       - 6066
     ports:
       #- 4040:4040
       #- 6066:6066
       - 7077:7077
       - 8070:8070
       - 8076:8076
     volumes:
       - ./spark/conf/master:/conf
       #- ./spark/data:/tmp/data
       #- ./zeppelin/notebooks:/usr/zeppelin/notebook
       #- ./zeppelin/data:/usr/zeppelin/data
   #worker_1:
   #  image: gettyimages/spark
   #  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
   #  hostname: worker_1
   #  environment:
   #    SPARK_CONF_DIR: /conf
   #    SPARK_WORKER_CORES: 1
   #    SPARK_WORKER_MEMORY: 1g
   #    SPARK_WORKER_PORT: 8881
   #    SPARK_WORKER_WEBUI_PORT: 8081
   #    SPARK_PUBLIC_DNS: localhost
   #  links:
   #    - master
   #  expose:
   #    - 7012
   #    - 7013
   #    - 7014
   #    - 7015
   #    - 7016
   #    - 8881
   #  #ports:
   #    #- 8076:8081
   #  volumes:
   #    - ./spark/conf/worker:/conf
   #    - ./spark/data:/tmp/data
   #worker_2:
   #  image: gettyimages/spark
   #  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
   #  hostname: worker_2
   #  environment:
   #    SPARK_CONF_DIR: /conf
   #    SPARK_WORKER_CORES: 1
   #    SPARK_WORKER_MEMORY: 1g
   #    SPARK_WORKER_PORT: 8881
   #    SPARK_WORKER_WEBUI_PORT: 8081
   #    SPARK_PUBLIC_DNS: localhost
   #  links:
   #    - master
   #  expose:
   #    - 7012
   #    - 7013
   #    - 7014
   #    - 7015
   #    - 7016
   #    - 8881
   #  ports:
   #    - 8077:8081
   #  volumes:
   #    - ./spark/conf/worker:/conf
   #    - ./spark/data:/tmp/data
