version: '2'
services:
   nifi:
       image: mkobit/nifi
       ports:
       - "8073:8080"
       - "8074:8081"
       volumes:
        - ./nifi:/nifi
   cassandra:
       image: cassandra
       hostname: cassandra
       expose:
         - 9042
         - 7000
       #ports:
       #- 7000:7000
       volumes:
       - ./cassandra:/cassandra
       - ./cassandra/CassandraData:/var/lib/cassandra
   master:
     image: dylanmei/zeppelin
     command: bash -c "/usr/spark-2.0.1/bin/spark-class org.apache.spark.deploy.master.Master -h master & /usr/zeppelin/bin/zeppelin.sh"
     # & /usr/zeppelin/bin/zeppelin.sh"
     # /usr/zeppelin/bin/install-interpreter.sh --name cassandra
     hostname: master
     environment:
       ZEPPELIN_PORT: 8080
       MASTER: spark://master:7077
       #MASTER: local[*]
       SPARK_CONF_DIR: /conf
       SPARK_PUBLIC_DNS: localhost
       SPARK_MASTER_WEBUI_PORT: 8075
       SPARK_SUBMIT_OPTIONS: " --packages com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M3"
     expose:
       - 7001
       - 7002
       - 7003
       - 7004
       - 7005
       - 7006
       - 7077
       - 6066
     ports:
       - 4040:4040
       - 6066:6066
       - 7077:7077
       - 8078:8080
       - 8075:8075
     volumes:
       - ./spark/conf/master:/conf
       - ./spark/data:/tmp/data
       - ./zeppelin/notebooks:/usr/zeppelin/notebook
       - ./zeppelin/data:/usr/zeppelin/data
   worker_1:
     image: gettyimages/spark
     command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
     hostname: worker_1
     environment:
       SPARK_CONF_DIR: /conf
       SPARK_WORKER_CORES: 1
       SPARK_WORKER_MEMORY: 1g
       SPARK_WORKER_PORT: 8881
       SPARK_WORKER_WEBUI_PORT: 8081
       SPARK_PUBLIC_DNS: localhost
     links:
       - master
     expose:
       - 7012
       - 7013
       - 7014
       - 7015
       - 7016
       - 8881
     volumes:
       - ./spark/conf/worker:/conf
       - ./spark/data:/tmp/data
   kafka:
     image: spotify/kafka
     hostname: kafka
     #command: sh /kafka/create_test_topic.sh
     environment:
       - KAFKA=localhost:9092
       - ZOOKEEPER=localhost:2181
       - KAFKA_CREATE_TOPICS="test"
     expose:
       - "2181"
       - "9092"
     #ports:
       #- 2181:2181
       #- 9092:9092
     volumes:
     - ./kafka:/kafka
